

class RedshiftNamingHelper:
    def check_reserved_keyword(name: str):
        reserved = "AES128, AES256, ALL, ALLOWOVERWRITE, ANALYSE, ANALYZE, AND, ANY, ARRAY, AS, ASC, AUTHORIZATION, BACKUP, BETWEEN, BINARY, BLANKSASNULL, BOTH, BYTEDICT, BZIP2, CASE, CAST, CHECK, COLLATE, COLUMN, CONSTRAINT, CREATE, CREDENTIALS, CROSS, CURRENT_DATE, CURRENT_TIME, CURRENT_TIMESTAMP, CURRENT_USER, CURRENT_USER_ID, DEFAULT, DEFERRABLE, DEFLATE, DEFRAG, DELTA, DELTA32K, DESC, DISABLE, DISTINCT, DO, ELSE, EMPTYASNULL, ENABLE, ENCODE, ENCRYPT, ENCRYPTION, END, EXCEPT, EXPLICIT, FALSE, FOR, FOREIGN, FREEZE, FROM, FULL, GLOBALDICT256, GLOBALDICT64K, GRANT, GROUP, GZIP, HAVING, IDENTITY, IGNORE, ILIKE, IN, INITIALLY, INNER, INTERSECT, INTO, IS, ISNULL, JOIN, LANGUAGE, LEADING, LEFT, LIKE, LIMIT, LOCALTIME, LOCALTIMESTAMP, LUN, LUNS, LZO, LZOP, MINUS, MOSTLY13, MOSTLY32, MOSTLY8, NATURAL, NEW, NOT, NOTNULL, NULL, NULLS, OFF, OFFLINE, OFFSET, OID, OLD, ON, ONLY, OPEN, OR, ORDER, OUTER, OVERLAPS, PARALLEL, PARTITION, PERCENT, PERMISSIONS, PLACING, PRIMARY, RAW, READRATIO, RECOVER, REFERENCES, RESPECT, REJECTLOG, RESORT, RESTORE, RIGHT, SELECT, SESSION_USER, SIMILAR, SNAPSHOT , SOME, SYSDATE, SYSTEM, TABLE, TAG, TDES, TEXT255, TEXT32K, THEN, TIMESTAMP, TO, TOP, TRAILING, TRUE, TRUNCATECOLUMNS, UNION, UNIQUE, USER, USING, VERBOSE, WALLET, WHEN, WHERE, WITH, WITHOUT".split()

        reserved = [x.strip(',') for x in reserved]
        return not (name.upper() in reserved)


    def check_valid_chars():

        # lower case chars, numbers, periods, dashes
        elif not bucket_name.islower():
            return tuple([False, 'bucket name cannot contain upper case characters'])

        elif not bool(re.match(r"^[a-z0-9\-\.]*$", bucket_name)):
            return tuple([False, 'bucket name can only contain lower case chars, numbers, dashes and periods'])
